<div class="section-footer">
    <div data-section-id="footer" data-section-type="footer-section">
        <div class="site-footer">
            <div id="scroll-over"><i class="fa fa-angle-up custom"></i></div>
            <div class="wrapper">
                <div class="grid row">
                    <div class="col box box-1 box-first  layout-6 social">
                        <img src="//cdn.shopify.com/s/files/1/0003/2820/4319/files/footer1_280x.png?v=1532692003" class="secondary_logo" alt="AitaiKuji">
                        <ul class="social-icons">
                            <li>
                                <a href="#" title="AitaiKuji on Twitter">
                                <span class="icon-fallback-text">
                                    <span class="icon icon-twitter" aria-hidden="true">
                                        <i class="fa fa-twitter"></i>
                                    </span>
                                    <span class="fallback-text">Twitter</span>
                                </span>
                                </a>
                            </li>
                            <li>
                                <a href="#" title="AitaiKuji on Facebook">
                                <span class="icon-fallback-text">
                                    <span class="icon icon-facebook" aria-hidden="true">
                                        <i class="fa fa-facebook"></i>
                                    </span>
                                    <span class="fallback-text">Facebook</span>
                                </span>
                                </a>
                            </li>
                            <li>
                                <a href="#" title="AitaiKuji on Instagram">
                                <span class="icon-fallback-text">
                                    <span class="icon icon-instagram" aria-hidden="true">
                                        <i class="fa fa-instagram"></i>
                                    </span>
                                    <span class="fallback-text">Instagram</span>
                                </span>
                                </a>
                            </li>
                            <li>
                                <a href="#" title="AitaiKuji on Tumblr">
                                <span class="icon-fallback-text">
                                    <span class="icon icon-tumblr" aria-hidden="true">
                                        <i class="fa fa-tumblr"></i>
                                    </span>
                                    <span class="fallback-text">Tumblr</span>
                                </span>
                                </a>
                            </li>
                        </ul>
                    </div>
                    <div class="col box box-2   layout-6 menu" role="navigation" aria-labelledby="nav-account">
                        <h4 id="nav-account">Account</h4>
                        <ul>
                            <li class="">
                                <a href="#">Login</a>
                            </li>
                            <li class="">
                            <a href="#">Order Status</a>  
                            </li>
                            <li class="">
                            <a href="#">Create Account</a>
                            </li>
                            <li class="">
                            <a href="#">Subscribe</a>
                            </li>
                        </ul>
                    </div>
                    <div class="col box box-3   layout-6 menu" role="navigation" aria-labelledby="nav-help">
                        <h4 id="nav-help">HELP</h4>
                        <ul>
                            <li class="">
                            <a href="/pages/faq">FAQ</a>
                            </li>
                            <li class="">
                            <a href="/blogs/news">News</a> 
                            </li>
                            <li class="">
                            <a href="#">Shipping Info</a>
                            </li>
                            <li class="">
                            <a href="/pages/contact">Contact Us</a>
                            </li>
                        </ul>
                    </div>
                    <div class="col box box-4   layout-6 menu" role="navigation" aria-labelledby="nav-info">
                        <h4 id="nav-info">INFO</h4>
                        <ul>
                            <li class="">
                            <a href="/pages/about-us">About us</a>
                            </li>
                            <li class="">
                            <a href="#">Audrey(CEO)</a>
                            </li>
                            <li class="">
                            <a href="#">Meet the team</a>
                            </li>
                        </ul>
                    </div>
                    <div class="col box box-5   layout-6 menu" role="navigation" aria-labelledby="nav-business-hours">
                        <h4 id="nav-business-hours">BUSINESS HOURS</h4>
                        <p>
                            Monday-Friday 10:00am - 6:00pm JST
                            Closed on Saturday, Sunday and Holidays
                        </p>
                        <ul liquid="" error="" (line="" 34):="" comparison="" of="" string="" with="" 1="" failed="">
                        </ul>
                    </div>
                    <div class="col box box-6  box-last layout-6 newsletter">
                        <div class="offer-message">
                            <h4>Newsletter</h4>
                        </div>
                        <div class="offer-email">
                            <form method="post" action="/contact#newsletter-footer" id="newsletter-footer" accept-charset="UTF-8" class="contact-form"><input type="hidden" name="form_type" value="customer"><input type="hidden" name="utf8" value="✓">
                            

                            
                                <input type="hidden" name="contact[tags]" value="prospect, email subscribe, footer">
                                <div class="input-row">
                                <div class="input-wrapper">
                                    <input type="email" name="contact[email]" id="email" placeholder="email@example.com" class="input-group-field" required="">
                                </div>
                                <div class="button-wrapper">
                                    <button type="submit" id="subscribe" class="btn">SUBSCRIBE</button>
                                </div>
                                </div>
                            
                            </form>
                        </div>
                    </div>
                </div>
            <p class="copyright">Copyright © 2019, <a href="/" title="">AitaiKuji</a> Japan. All rights reserved </p>
            </div>
        </div>
    </div>
</div>