<div class="group-icon-dafault">
    <span class="span-icon">
        <i class="fa fa-search"></i>
    </span>
    <span class="span-icon">
        <i class="fa fa-user"></i>
    </span>
    <span class="span-icon">
        <i class="fa fa-shopping-cart"></i>
    </span>
</div>
<div class="group-icon-social">
    <span class="span-icon">
        <i class="fa fa-facebook"></i>
    </span>
    <span class="span-icon">
        <i class="fa fa-twitter"></i>
    </span>
    <span class="span-icon">
        <i class="fa fa-google-plus"></i>
    </span>
    <span class="span-icon">
        <i class="fa fa-youtube-play"></i>
    </span>
</div>