<?php
use Magento\Framework\App\Action\Action;
?>

<?php
$_productCollection = $block->getProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$uniqId = uniqid('block_');
?>
<script>
var data_<?php echo $uniqId ?> = <?php echo json_encode($block->getData()) ?>;
</script>

<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?php /* @escapeNotVerified */ echo __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
    <?php
		$descLength = 100;
		$viewMode = 'grid';
		$image = 'category_page_grid';
		$image_hover = 'category_page_grid_hover';
		$showDescription = false;
		$title = $block->getTitle() ? __($block->getTitle()) : '';
		$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
		$classid = md5(json_encode($block->getData()));
		$labelHelper = $this->helper('Codazon\ProductLabel\Helper\Data');
		$pos = $block->getPositioned();
		$wLHelper = $this->helper('Magento\Wishlist\Helper\Data'); //getWishlistItemCollection
		$uniqId = uniqid('block_');
		global $wLItemArray;
		if( empty($wLItemArray) ){
			$wLCollection = $wLHelper->getWishlistItemCollection();
			$wLItemArray = [-1];
			foreach($wLCollection as $wLItem){
				$wLItemArray[] = $wLItem->getProductId();	
			}
		}
    ?>
		<?php foreach ($_productCollection as $_product){ ?>
			<?php $productImage = $block->getImage($_product, $image); ?>
				<div class="items">
					<div class="slideshow-item">
						<a href="<?=$_product->getProductUrl()?>" title="<?=$_product->getName()?>">
							<div class="tabs-image">
								<?php echo $productImage->toHtml(); ?>            
							</div>
							<div class="tabs-title">
								<p><?=$_product->getName()?></p>
							</div>
						</a>
						<?php $postParams = $block->getAddToCartPostParams($_product); ?>
						<form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
							<input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $_product->getId() ?>" />
							<input type="hidden" name="selected_configurable_option" value="" />
							<input type="hidden" name="related_product" id="related-products-field" value="" />
							<input type="hidden" name="item"  value="<?= /* @noEscape */ $block->getRequest()->getParam('id') ?>" />
							<div class="grid-product color-grey">
								<span class="product-price" id="price-preview">¥<?=$_product->getPrice()?></span>
							</div>   	
							<div class="add-to cart-section">
								<input type="hidden" name="id" data-productid="744630288484" class="product-select" value="8136411578468" data-variant-title="A / Orange">
								<button type="submit" value="Add To Cart" class="action_button add_to_cart"><span class="text">Add to Cart</span></button>
							</div>
						</form>   
					</div>  
				</div>
				<script type="text/x-magento-init">
				{
					"[data-role=tocart-form], .form.map.checkout": {
						"catalogAddToCart": {
							"bindSubmit": true
						}
					}
				}
				</script>
		<?php } ?>
<?php endif; ?>
<div style="clear : both"></div>

<script type="text/x-magento-init">
{
	"*":{
		"js/customjs": {}
	}
}
</script>
